DROP TABLE IF EXISTS summoner;
DROP TABLE IF EXISTS match_table; --"match" is an sqlite keyword
DROP TABLE IF EXISTS participant;

CREATE TABLE summoner (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_name TEXT NOT NULL,
    tag_line TEXT NOT NULL,
    profile_icon_id INTEGER NOT NULL,
    summoner_level INTEGER NOT NULL,
    solo_tier TEXT,
    solo_rank TEXT,
    solo_league_points INTEGER,
    solo_wins INTEGER,
    solo_losses INTEGER,
    flex_tier TEXT,
    flex_rank TEXT,
    flex_league_points INTEGER,
    flex_wins INTEGER,
    flex_losses INTEGER,
    last_update INTEGER NOT NULL --used to timegate user requests to limit api rate to riot api.
);

CREATE TABLE match_table (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    match_id TEXT UNIQUE NOT NULL, -- unique match_id is nice for when some player already requests said match and some other player from that same game requests it, too.
    end_of_game_result TEXT NOT NULL,
    game_creation INTEGER NOT NULL,
    game_duration INTEGER NOT NULL,
    game_end_timestamp INTEGER NOT NULL,
    game_id INTEGER NOT NULL,
    game_mode TEXT NOT NULL,
    game_name TEXT NOT NULL,
    game_start_timestamp INTEGER NOT NULL,
    game_type TEXT NOT NULL,
    game_version TEXT NOT NULL,
    map_id INTEGER NOT NULL,
    platform_id TEXT NOT NULL,
    queue_id INTEGER NOT NULL
);

CREATE TABLE participant (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    assists INTEGER NOT NULL,
    baron_kills INT NOT NULL,
    bounty_level INT NOT NULL,
    champ_experience INT NOT NULL,
    champ_level INTEGER NOT NULL,
    champion_id INTEGER NOT NULL,
    champion_name TEXT NOT NULL,
    consumables_purchased TEXT NOT NULL,
    damage_dealt_to_buildings INTEGER NOT NULL,
    damage_dealt_to_objectives INTEGER NOT NULL,
    damage_dealt_to_turrets INTEGER NOT NULL,
    damage_self_mitigated INTEGER NOT NULL,
    deaths INTEGER NOT NULL,
    detector_wards_placed INTEGER NOT NULL,
    double_kills INTEGER NOT NULL,
    dragon_kills INTEGER NOT NULL,
    first_blood_assist INTEGER NOT NULL,
    first_blood_kill INTEGER NOT NULL,
    first_tower_assist INTEGER NOT NULL,
    first_tower_kill INTEGER NOT NULL,
    game_ended_in_surrender INTEGER NOT NULL,
    gold_earned INTEGER NOT NULL,
    gold_spent INTEGER NOT NULL,
    individual_position TEXT NOT NULL,
    inhibitor_kills INTEGER NOT NULL,
    inhibitor_takedowns INTEGER NOT NULL,
    inhibitors_lost INTEGER NOT NULL,
    item0 INTEGER NOT NULL,
    item1 INTEGER NOT NULL,
    item2 INTEGER NOT NULL,
    item3 INTEGER NOT NULL,
    item4 INTEGER NOT NULL,
    item5 INTEGER NOT NULL,
    item6 INTEGER NOT NULL,
    items_purchased INTEGER NOT NULL,
    kills INTEGER NOT NULL,
    lane TEXT NOT NULL,
    largest_critical_strike INTEGER NOT NULL,
    largest_killing_spree INTEGER NOT NULL,
    largest_multi_kill INTEGER NOT NULL,
    longest_time_spent_living INTEGER NOT NULL,
    magic_damage_dealt INTEGER NOT NULL,
    magic_damage_dealt_to_champions INTEGER NOT NULL,
    magic_damage_taken INTEGER NOT NULL,
    neutral_minions_killed INTEGER NOT NULL,
    objectives_stolen INTEGER NOT NULL,
    objectives_stolen_assists INTEGER NOT NULL,
    penta_kills INTEGER NOT NULL,
    physical_damage_dealt INTEGER NOT NULL,
    physical_damage_dealt_to_champions INTEGER NOT NULL,
    physical_damage_taken INTEGER NOT NULL,
    profile_icon INTEGER NOT NULL,
    puuid TEXT NOT NULL,
    quadra_kills INTEGER NOT NULL,
    riot_id_game_name TEXT NOT NULL,
    riot_id_tag_line TEXT NOT NULL,
    player_role TEXT NOT NULL, --role
    sight_wards_bought_in_game INTEGER NOT NULL,
    spell1_casts INTEGER NOT NULL,
    spell2_casts INTEGER NOT NULL,
    spell3_casts INTEGER NOT NULL,
    spell4_casts INTEGER NOT NULL,
    summoner1_casts INTEGER NOT NULL,
    summoner1_id INTEGER NOT NULL,
    summoner2_casts INTEGER NOT NULL,
    summoner2_id INTEGER NOT NULL,
    summoner_id TEXT NOT NULL,
    summoner_level INTEGER NOT NULL,
    team_id INTEGER NOT NULL,
    time_CCing_others INTEGER NOT NULL,
    time_played INTEGER NOT NULL,
    total_ally_jungle_minions_killed INTEGER NOT NULL,
    total_damage_dealt INTEGER NOT NULL,
    total_damage_dealt_to_champions INTEGER NOT NULL,
    total_damage_shielded_on_teammates INTEGER NOT NULL,
    total_damage_taken INTEGER NOT NULL,
    total_enemy_jungle_minions_killed INTEGER NOT NULL,
    total_heal INTEGER NOT NULL,
    total_heals_on_teammates INTEGER NOT NULL,
    total_minions_killed INTEGER NOT NULL,
    total_time_CC_dealt INTEGER NOT NULL,
    total_time_spent_dead INTEGER NOT NULL,
    total_units_healed INTEGER NOT NULL,
    triple_kills INTEGER NOT NULL,
    true_damage_dealt INTEGER NOT NULL,
    true_damage_dealt_to_champions INTEGER NOT NULL,
    true_damage_taken INTEGER NOT NULL,
    turret_kills INTEGER NOT NULL,
    turret_takedowns INTEGER NOT NULL,
    turrets_lost INTEGER NOT NULL,
    unreal_kills INTEGER NOT NULL,
    vision_score INTEGER NOT NULL,
    vision_wards_bought_in_game INTEGER NOT NULL,
    wards_killed INTEGER NOT NULL,
    wards_placed INTEGER NOT NULL,
    win INTEGER NOT NULL,
    defense_perk INTEGER NOT NULL,
    flex_perk INTEGER NOT NULL,
    offense_perk INTEGER NOT NULL,
    primary_style_perk INTEGER NOT NULL,
    sub_style_perk INTEGER NOT NULL,
    match_id INTEGER NOT NULL,
    FOREIGN KEY (match_id) REFERENCES match_table (id)
);